version: '3'
services:
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: 'toury'
      POSTGRES_USER: 'toury'
      POSTGRES_PASSWORD: '111'
    ports:
      - 54328:5432

  db_test:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: 'toury_test'
      POSTGRES_USER: 'toury'
      POSTGRES_PASSWORD: '111'
    ports:
      - 54329:5432
